name: x86_64-linux

on:
  push:
    branches:
      - master

jobs:
  main:
    timeout-minutes: 180
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: DeterminateSystems/nix-installer-action@main

      - name: test emulator
        run: |
          ./build-emulator-and-check-arch.sh